# Caterpillar Tube Pricing

## Introduction
Walking past a construction site, Caterpillar's signature bright yellow machinery is one of the first things you'll notice. Caterpillar sells an enormous variety of larger-than-life construction and mining equipment to companies across the globe. Each machine relies on a complex set of tubes to keep the forklift lifting, the loader loading, and the bulldozer from dozing off. 

Like snowflakes, it's difficult to find two tubes in Caterpillar's diverse catalogue of machinery that are exactly alike. Tubes can vary across a number of dimensions, including base materials, number of bends, bend radius, bolt patterns, and end types.

Currently, Caterpillar relies on a variety of suppliers to manufacture these tube assemblies, each having their own unique pricing model. This competition provides detailed tube, component, and annual volume datasets, and challenges you to predict the price a supplier will quote for a given tube assembly.


## Project Summary
This project has the purpose to predict how a supplier will quote a price on a given tube assembly. Knowing this information in advance we can determine the optimal quote which will maximize the profits of the company.

The overall goal of this project is to predict quotation price given by a supplier with at least 95% of accuracy. The input given for this project is a dataset containing information about tube assemblies, price quotations and a set of components. 


## Project Development Process
1. We will describe the purpose of the project and establish technological requirements needed to archive the main goal of this project.
2. From the dataset, we will write a code book to describe the files and data.
3. We will deduce the database relational scheme from the dataset and build the database using MySQL and Python.
4. We will then start the data analysis.
    a. Study and find relations between variables.
    b. Find a method and explain why we use that method
    c. Build a model to predict how a supplier will quote a price on a given tube assembly
    d. Produce a report with results from the model as output
    e. Compare the results with real good results
    f. If the results are worst than the real ones, then we will identify why it's worst and start again at step 5.
    g. Even if the model failed, we will always keep trace of our research in a document.
5. When our method is proven better, we will conclude by showing graphics and explain the advantage of using our method with business terms.
